---
name: ci

on:
  push:
    branches: [dev]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [dev]
    paths-ignore:
      - '**.md'

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node-version: [20.x]
    runs-on: ${{ matrix.os }}
    env:
      NODE_ADDRESS: http://localhost:7777/rpc
      EVENT_ADDRESS: http://localhost:9999/events/main
      KMS_ADDRESS: http://localhost:8080
      DEBUG: false
      # WARNING: These accounts, and their private keys, are publicly known.
      # Any funds sent to them on Mainnet or any other live network WILL BE LOST.
      FAUCET_PRIVATE_KEY: '-----BEGIN PRIVATE KEY----- MC4CAQAwBQYDK2VwBCIEII8ULlk1CJ12ZQ+bScjBt/IxMAZNggClWqK56D1/7CbI -----END PRIVATE KEY-----'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a #v3.4.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci
        working-directory: ./src/

      - name: Unit Tests
        run: npm run test:cov
        working-directory: ./src/

      - name: Casper node launcher js
        run: npx casper-node-launcher-js node --daemon

      - name: Docker Build and run
        run: docker network create casper-equitybrix-network && docker compose -f docker-compose.test.yml up -d
      - name: E2e Tests
        run: npm run test:e2e
        working-directory: ./src/
