# version: "3.7"
services:

  nginx:
    image: nginx:latest
    ports:
      - "8282:80"
    volumes:
      - shared-files-platform:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-platform
    networks:
      - dev

  php-platform:
    build:
      context: ./platform # Path to the directory containing your Dockerfile and source code
      dockerfile: Dockerfile # Name of your Dockerfile if it's not named 'Dockerfile'
    image: laravel-platform-webhook:latest
    container_name: "php-platform"
    restart: always
    env_file:
      - .env.platform
    ports:
      - "9001:9000"
    volumes:
      - shared-files-platform:/var/www/html
    # environment:
    #   # Define environment variables from ConfigMap here
    #   # Example:
    #   # ENV_VAR_NAME: ${ENV_VAR_NAME}
    user: "2000:2000"  # Adjust user/group ID as needed
    networks:
      - dev

  init:
    depends_on:
      - php-platform
    image: laravel-platform-webhook:latest
    env_file:
      - .env.platform
    command: ["/bin/sh", "-c", "cp -r /var/www/html/. /tmp"]
    volumes:
      - shared-files-platform:/tmp
    networks:
      - dev

  set-permissions:
    depends_on:
      - init
    image: busybox
    command: ["sh", "-c", "chmod -R 777 /var/www/html/storage && chmod -R 777 /var/www/html/public && chmod -R 777 /var/www/html/node_modules && chmod -R 777 /var/www/html/database && chmod -R 777 /var/www/html/bootstrap/cache && chmod 666 /var/www/html/composer.json && chmod 666 /var/www/html/composer.lock && chmod -R 777 /var/www/html/vendor && chmod -R 777 /var/www/html/config && chmod -R 777 /var/www/html/resources"]
    volumes:
      - shared-files-platform:/var/www/html
    networks:
      - dev

volumes:
  shared-files-platform:
    driver: local
  # nginx-config-volume:
  #   driver: local
  # nginx-config:
  #   driver: local

networks:
  dev:
    driver: bridge
    name: dev